name:                ghcaniuse
version:             0.3.0.0
github:              "damianfral/ghcaniuse"
license:             BSD3
author:              "damianfral"
maintainer:          "huevofritopamojarpan@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
  - base
  - basic-prelude
  - scalpel
  - lens
  - parsec
  - time
  - turtle
  - text
  - aeson
  - bytestring
  - unordered-containers
  - lucid
  - transformers

library:
  source-dirs: ./src/

executables:

  ghcaniuse:
    main         : Main.hs
    source-dirs  : ./app/
    dependencies :
      - ghcaniuse

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
- -threaded
- -rtsopts -with-rtsopts=-N
